### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [singcodes/BundleInfos#1]
<img width="364" alt="screen shot 2016-06-24 at 10 28 35 am" src="https://cloud.githubusercontent.com/assets/6511079/16338978/73353e24-39f6-11e6-8121-b10ea6e60c5d.png">
Should be something like:

> Simple getter for bundle informations, written in Swift 🔶

**Comment by oozoofrog** [comment]
thanks!
I added simple description 😀
