### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by lfarah** [singcodes/BundleInfos#2]
Hey @singcodes, your library is really interesting.

The only problem I found was the `README.md`, which is a little bit confusing.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to organize the lib so we can approve [your pull request](https://github.com/vsouza/awesome-ios/pull/909)

What are your thoughts?

**Comment by oozoofrog** [comment]
Thank you @lfarah  for suggestion. It's very help to me. I shame didn't know that.

**Comment by oozoofrog** [comment]
I'm updates README.md. If more lackings, plz let me know.

and... thank you @lfarah  for the beautiful templates. 
have a good day~

**Comment by lfarah** [comment]
You're welcome!
I'm glad I could help 😄
